using System;
using System.ComponentModel;

namespace NDMSInvestigation.Entities
{
	/// <summary>
	///		The data structure representation of the 'QuestionGroup' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IQuestionGroup 
	{
		/// <summary>			
		/// GroupId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "QuestionGroup"</remarks>
		System.Int32 GroupId { get; set; }
				
		
		
		/// <summary>
		/// GroupName : 
		/// </summary>
		System.String  GroupName  { get; set; }
		
		/// <summary>
		/// GroupDescription : 
		/// </summary>
		System.String  GroupDescription  { get; set; }
		
		/// <summary>
		/// OrderNumber : 
		/// </summary>
		System.Int32?  OrderNumber  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _questionDetailsGroupId
		/// </summary>	
		TList<QuestionDetails> QuestionDetailsCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _resultGroupId
		/// </summary>	
		TList<Result> ResultCollection {  get;  set;}	

		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the junction table userIdAspnetUsersCollectionFromResult
		/// </summary>	
		TList<AspnetUsers> UserIdAspnetUsersCollection_From_Result { get; set; }	

		#endregion Data Properties

	}
}


