
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file Results.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;
using Microsoft.Practices.EnterpriseLibrary.Validation;

using NDMSInvestigation.Entities.Validation;
#endregion

namespace NDMSInvestigation.Entities
{
	///<summary>
	/// An object representation of the 'Results' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class ResultsBase : EntityBase, IResults, IEntityId<ResultsKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private ResultsEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private ResultsEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private ResultsEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Results> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event ResultsEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event ResultsEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="ResultsBase"/> instance.
		///</summary>
		public ResultsBase()
		{
			this.entityData = new ResultsEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="ResultsBase"/> instance.
		///</summary>
		///<param name="_userId"></param>
		///<param name="_groupId"></param>
		///<param name="_groupMark"></param>
		///<param name="_createdDate"></param>
		///<param name="_testTimes"></param>
		public ResultsBase(System.Guid _userId, System.Int32 _groupId, System.Int32? _groupMark, 
			System.DateTime? _createdDate, System.Int32? _testTimes)
		{
			this.entityData = new ResultsEntityData();
			this.backupData = null;

			this.UserId = _userId;
			this.GroupId = _groupId;
			this.GroupMark = _groupMark;
			this.CreatedDate = _createdDate;
			this.TestTimes = _testTimes;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Results"/> instance.
		///</summary>
		///<param name="_userId"></param>
		///<param name="_groupId"></param>
		///<param name="_groupMark"></param>
		///<param name="_createdDate"></param>
		///<param name="_testTimes"></param>
		public static Results CreateResults(System.Guid _userId, System.Int32 _groupId, System.Int32? _groupMark, 
			System.DateTime? _createdDate, System.Int32? _testTimes)
		{
			Results newResults = new Results();
			newResults.UserId = _userId;
			newResults.GroupId = _groupId;
			newResults.GroupMark = _groupMark;
			newResults.CreatedDate = _createdDate;
			newResults.TestTimes = _testTimes;
			return newResults;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the UserId property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Guid UserId
		{
			get
			{
				return this.entityData.UserId; 
			}
			
			set
			{
				if (this.entityData.UserId == value)
					return;
					
				OnColumnChanging(ResultsColumn.UserId, this.entityData.UserId);
				this.entityData.UserId = value;
				this.EntityId.UserId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ResultsColumn.UserId, this.entityData.UserId);
				OnPropertyChanged("UserId");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the UserId property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the UserId property.</remarks>
		/// <value>This type is uniqueidentifier</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Guid OriginalUserId
		{
			get { return this.entityData.OriginalUserId; }
			set { this.entityData.OriginalUserId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the GroupId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Int32 GroupId
		{
			get
			{
				return this.entityData.GroupId; 
			}
			
			set
			{
				if (this.entityData.GroupId == value)
					return;
					
				OnColumnChanging(ResultsColumn.GroupId, this.entityData.GroupId);
				this.entityData.GroupId = value;
				this.EntityId.GroupId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ResultsColumn.GroupId, this.entityData.GroupId);
				OnPropertyChanged("GroupId");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the GroupId property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the GroupId property.</remarks>
		/// <value>This type is int</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Int32 OriginalGroupId
		{
			get { return this.entityData.OriginalGroupId; }
			set { this.entityData.OriginalGroupId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the GroupMark property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsGroupMarkNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? GroupMark
		{
			get
			{
				return this.entityData.GroupMark; 
			}
			
			set
			{
				if (this.entityData.GroupMark == value)
					return;
					
				OnColumnChanging(ResultsColumn.GroupMark, this.entityData.GroupMark);
				this.entityData.GroupMark = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ResultsColumn.GroupMark, this.entityData.GroupMark);
				OnPropertyChanged("GroupMark");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CreatedDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsCreatedDateNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? CreatedDate
		{
			get
			{
				return this.entityData.CreatedDate; 
			}
			
			set
			{
				if (this.entityData.CreatedDate == value)
					return;
					
				OnColumnChanging(ResultsColumn.CreatedDate, this.entityData.CreatedDate);
				this.entityData.CreatedDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ResultsColumn.CreatedDate, this.entityData.CreatedDate);
				OnPropertyChanged("CreatedDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TestTimes property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsTestTimesNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? TestTimes
		{
			get
			{
				return this.entityData.TestTimes; 
			}
			
			set
			{
				if (this.entityData.TestTimes == value)
					return;
					
				OnColumnChanging(ResultsColumn.TestTimes, this.entityData.TestTimes);
				this.entityData.TestTimes = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ResultsColumn.TestTimes, this.entityData.TestTimes);
				OnPropertyChanged("TestTimes");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="AspnetUsers"/>.
		/// </summary>
		/// <value>The source AspnetUsers for UserId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual AspnetUsers UserIdSource
      	{
            get { return entityData.UserIdSource; }
            set { entityData.UserIdSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="QuestionGroups"/>.
		/// </summary>
		/// <value>The source QuestionGroups for GroupId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual QuestionGroups GroupIdSource
      	{
            get { return entityData.GroupIdSource; }
            set { entityData.GroupIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "Results"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"UserId", "GroupId", "GroupMark", "CreatedDate", "TestTimes"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as ResultsEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Results) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Results>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Results);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Results Entity 
		///</summary>
		protected virtual Results Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			Results copy = new Results();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.UserId = this.UserId;
					copy.OriginalUserId = this.OriginalUserId;
				copy.GroupId = this.GroupId;
					copy.OriginalGroupId = this.OriginalGroupId;
				copy.GroupMark = this.GroupMark;
				copy.CreatedDate = this.CreatedDate;
				copy.TestTimes = this.TestTimes;
			
			if (this.UserIdSource != null && existingCopies.Contains(this.UserIdSource))
				copy.UserIdSource = existingCopies[this.UserIdSource] as AspnetUsers;
			else
				copy.UserIdSource = MakeCopyOf(this.UserIdSource, existingCopies) as AspnetUsers;
			if (this.GroupIdSource != null && existingCopies.Contains(this.GroupIdSource))
				copy.GroupIdSource = existingCopies[this.GroupIdSource] as QuestionGroups;
			else
				copy.GroupIdSource = MakeCopyOf(this.GroupIdSource, existingCopies) as QuestionGroups;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed Results Entity 
		///</summary>
		public virtual Results Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed Results Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Results DeepCopy()
		{
			return EntityHelper.Clone<Results>(this as Results);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as ResultsEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new ResultsEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as ResultsEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(ResultsColumn column)
		{
			switch(column)
			{
					case ResultsColumn.UserId:
					return entityData.UserId != _originalData.UserId;
					case ResultsColumn.GroupId:
					return entityData.GroupId != _originalData.GroupId;
					case ResultsColumn.GroupMark:
					return entityData.GroupMark != _originalData.GroupMark;
					case ResultsColumn.CreatedDate:
					return entityData.CreatedDate != _originalData.CreatedDate;
					case ResultsColumn.TestTimes:
					return entityData.TestTimes != _originalData.TestTimes;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< ResultsColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.UserId != _originalData.UserId;
			result = result || entityData.GroupId != _originalData.GroupId;
			result = result || entityData.GroupMark != _originalData.GroupMark;
			result = result || entityData.CreatedDate != _originalData.CreatedDate;
			result = result || entityData.TestTimes != _originalData.TestTimes;
			return result;
		}	
		
		///<summary>
		///  Returns a Results Entity with the original data.
		///</summary>
		public Results GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateResults(
				_originalData.UserId,
				_originalData.GroupId,
				_originalData.GroupMark,
				_originalData.CreatedDate,
				_originalData.TestTimes
				);
				
			return (Results)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="ResultsBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is ResultsBase)
				return ValueEquals(this, (ResultsBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="ResultsBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.UserId.GetHashCode() ^ 
					this.GroupId.GetHashCode() ^ 
					((this.GroupMark == null) ? string.Empty : this.GroupMark.ToString()).GetHashCode() ^ 
					((this.CreatedDate == null) ? string.Empty : this.CreatedDate.ToString()).GetHashCode() ^ 
					((this.TestTimes == null) ? string.Empty : this.TestTimes.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="ResultsBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(ResultsBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="ResultsBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="ResultsBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="ResultsBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(ResultsBase Object1, ResultsBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.UserId != Object2.UserId)
				equal = false;
			if (Object1.GroupId != Object2.GroupId)
				equal = false;
			if ( Object1.GroupMark != null && Object2.GroupMark != null )
			{
				if (Object1.GroupMark != Object2.GroupMark)
					equal = false;
			}
			else if (Object1.GroupMark == null ^ Object2.GroupMark == null )
			{
				equal = false;
			}
			if ( Object1.CreatedDate != null && Object2.CreatedDate != null )
			{
				if (Object1.CreatedDate != Object2.CreatedDate)
					equal = false;
			}
			else if (Object1.CreatedDate == null ^ Object2.CreatedDate == null )
			{
				equal = false;
			}
			if ( Object1.TestTimes != null && Object2.TestTimes != null )
			{
				if (Object1.TestTimes != Object2.TestTimes)
					equal = false;
			}
			else if (Object1.TestTimes == null ^ Object2.TestTimes == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((ResultsBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static ResultsComparer GetComparer()
        {
            return new ResultsComparer();
        }
        */

        // Comparer delegates back to Results
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Results rhs, ResultsColumn which)
        {
            switch (which)
            {
            	
            	
            	case ResultsColumn.UserId:
            		return this.UserId.CompareTo(rhs.UserId);
            		
            		                 
            	
            	
            	case ResultsColumn.GroupId:
            		return this.GroupId.CompareTo(rhs.GroupId);
            		
            		                 
            	
            	
            	case ResultsColumn.GroupMark:
            		return this.GroupMark.Value.CompareTo(rhs.GroupMark.Value);
            		
            		                 
            	
            	
            	case ResultsColumn.CreatedDate:
            		return this.CreatedDate.Value.CompareTo(rhs.CreatedDate.Value);
            		
            		                 
            	
            	
            	case ResultsColumn.TestTimes:
            		return this.TestTimes.Value.CompareTo(rhs.TestTimes.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<ResultsKey> Members
		
		// member variable for the EntityId property
		private ResultsKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual ResultsKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new ResultsKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Results")
					.Append("|").Append( this.UserId.ToString())
					.Append("|").Append( this.GroupId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{6}{5}- UserId: {0}{5}- GroupId: {1}{5}- GroupMark: {2}{5}- CreatedDate: {3}{5}- TestTimes: {4}{5}{7}", 
				this.UserId,
				this.GroupId,
				(this.GroupMark == null) ? string.Empty : this.GroupMark.ToString(),
				(this.CreatedDate == null) ? string.Empty : this.CreatedDate.ToString(),
				(this.TestTimes == null) ? string.Empty : this.TestTimes.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'Results' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class ResultsEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// UserId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Results"</remarks>
		public System.Guid UserId;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.Guid OriginalUserId;
		
		/// <summary>			
		/// GroupId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Results"</remarks>
		public System.Int32 GroupId;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.Int32 OriginalGroupId;
		
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// GroupMark : 
		/// </summary>
		public System.Int32?		  GroupMark = null;
		
		/// <summary>
		/// CreatedDate : 
		/// </summary>
		public System.DateTime?		  CreatedDate = null;
		
		/// <summary>
		/// TestTimes : 
		/// </summary>
		public System.Int32?		  TestTimes = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private AspnetUsers _userIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="AspnetUsers"/>.
		/// </summary>
		/// <value>The source AspnetUsers for UserId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual AspnetUsers UserIdSource
      	{
            get { return this._userIdSource; }
            set { this._userIdSource = value; }
      	}
		private QuestionGroups _groupIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="QuestionGroups"/>.
		/// </summary>
		/// <value>The source QuestionGroups for GroupId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual QuestionGroups GroupIdSource
      	{
            get { return this._groupIdSource; }
            set { this._groupIdSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			ResultsEntityData _tmp = new ResultsEntityData();
						
			_tmp.UserId = this.UserId;
			_tmp.OriginalUserId = this.OriginalUserId;
			_tmp.GroupId = this.GroupId;
			_tmp.OriginalGroupId = this.OriginalGroupId;
			
			_tmp.GroupMark = this.GroupMark;
			_tmp.CreatedDate = this.CreatedDate;
			_tmp.TestTimes = this.TestTimes;
			
			#region Source Parent Composite Entities
			if (this.UserIdSource != null)
				_tmp.UserIdSource = MakeCopyOf(this.UserIdSource) as AspnetUsers;
			if (this.GroupIdSource != null)
				_tmp.GroupIdSource = MakeCopyOf(this.GroupIdSource) as QuestionGroups;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			ResultsEntityData _tmp = new ResultsEntityData();
						
			_tmp.UserId = this.UserId;
			_tmp.OriginalUserId = this.OriginalUserId;
			_tmp.GroupId = this.GroupId;
			_tmp.OriginalGroupId = this.OriginalGroupId;
			
			_tmp.GroupMark = this.GroupMark;
			_tmp.CreatedDate = this.CreatedDate;
			_tmp.TestTimes = this.TestTimes;
			
			#region Source Parent Composite Entities
			if (this.UserIdSource != null && existingCopies.Contains(this.UserIdSource))
				_tmp.UserIdSource = existingCopies[this.UserIdSource] as AspnetUsers;
			else
				_tmp.UserIdSource = MakeCopyOf(this.UserIdSource, existingCopies) as AspnetUsers;
			if (this.GroupIdSource != null && existingCopies.Contains(this.GroupIdSource))
				_tmp.GroupIdSource = existingCopies[this.GroupIdSource] as QuestionGroups;
			else
				_tmp.GroupIdSource = MakeCopyOf(this.GroupIdSource, existingCopies) as QuestionGroups;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ResultsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(ResultsColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ResultsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(ResultsColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ResultsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(ResultsColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				ResultsEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new ResultsEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ResultsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(ResultsColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				ResultsEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new ResultsEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region ResultsEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Results"/> object.
	/// </remarks>
	public class ResultsEventArgs : System.EventArgs
	{
		private ResultsColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the ResultsEventArgs class.
		///</summary>
		public ResultsEventArgs(ResultsColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the ResultsEventArgs class.
		///</summary>
		public ResultsEventArgs(ResultsColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The ResultsColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="ResultsColumn" />
		public ResultsColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Results related events.
	///</summary>
	public delegate void ResultsEventHandler(object sender, ResultsEventArgs e);
	
	#region ResultsComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class ResultsComparer : System.Collections.Generic.IComparer<Results>
	{
		ResultsColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:ResultsComparer"/> class.
        /// </summary>
		public ResultsComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:ResultsComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public ResultsComparer(ResultsColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="Results"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="Results"/> to compare.</param>
        /// <param name="b">The second <c>Results</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Results a, Results b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Results entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Results a, Results b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public ResultsColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region ResultsKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Results"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class ResultsKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the ResultsKey class.
		/// </summary>
		public ResultsKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the ResultsKey class.
		/// </summary>
		public ResultsKey(ResultsBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.UserId = entity.UserId;
				this.GroupId = entity.GroupId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the ResultsKey class.
		/// </summary>
		public ResultsKey(System.Guid _userId, System.Int32 _groupId)
		{
			#region Init Properties

			this.UserId = _userId;
			this.GroupId = _groupId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private ResultsBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public ResultsBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the UserId property
		private System.Guid _userId;
		
		/// <summary>
		/// Gets or sets the UserId property.
		/// </summary>
		public System.Guid UserId
		{
			get { return _userId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.UserId = value;
				
				_userId = value;
			}
		}
		
		// member variable for the GroupId property
		private System.Int32 _groupId;
		
		/// <summary>
		/// Gets or sets the GroupId property.
		/// </summary>
		public System.Int32 GroupId
		{
			get { return _groupId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.GroupId = value;
				
				_groupId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				UserId = ( values["UserId"] != null ) ? (System.Guid) EntityUtil.ChangeType(values["UserId"], typeof(System.Guid)) : Guid.Empty;
				GroupId = ( values["GroupId"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["GroupId"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("UserId", UserId);
			values.Add("GroupId", GroupId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("UserId: {0}{2}GroupId: {1}{2}",
								UserId,
								GroupId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region ResultsColumn Enum
	
	/// <summary>
	/// Enumerate the Results columns.
	/// </summary>
	[Serializable]
	public enum ResultsColumn : int
	{
		/// <summary>
		/// UserId : 
		/// </summary>
		[EnumTextValue("UserId")]
		[ColumnEnum("UserId", typeof(System.Guid), System.Data.DbType.Guid, true, false, false)]
		UserId = 1,
		/// <summary>
		/// GroupId : 
		/// </summary>
		[EnumTextValue("GroupId")]
		[ColumnEnum("GroupId", typeof(System.Int32), System.Data.DbType.Int32, true, false, false)]
		GroupId = 2,
		/// <summary>
		/// GroupMark : 
		/// </summary>
		[EnumTextValue("GroupMark")]
		[ColumnEnum("GroupMark", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		GroupMark = 3,
		/// <summary>
		/// CreatedDate : 
		/// </summary>
		[EnumTextValue("CreatedDate")]
		[ColumnEnum("CreatedDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		CreatedDate = 4,
		/// <summary>
		/// TestTimes : 
		/// </summary>
		[EnumTextValue("TestTimes")]
		[ColumnEnum("TestTimes", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		TestTimes = 5
	}//End enum

	#endregion ResultsColumn Enum

} // end namespace
