
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file AspnetRoles.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using Microsoft.Practices.EnterpriseLibrary.Validation.Validators;
using Microsoft.Practices.EnterpriseLibrary.Validation;

using NDMSInvestigation.Entities.Validation;
#endregion

namespace NDMSInvestigation.Entities
{
	///<summary>
	/// An object representation of the 'aspnet_Roles' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class AspnetRolesBase : EntityBase, IAspnetRoles, IEntityId<AspnetRolesKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private AspnetRolesEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private AspnetRolesEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private AspnetRolesEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<AspnetRoles> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event AspnetRolesEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event AspnetRolesEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="AspnetRolesBase"/> instance.
		///</summary>
		public AspnetRolesBase()
		{
			this.entityData = new AspnetRolesEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="AspnetRolesBase"/> instance.
		///</summary>
		///<param name="_applicationId"></param>
		///<param name="_roleId"></param>
		///<param name="_roleName"></param>
		///<param name="_loweredRoleName"></param>
		///<param name="_description"></param>
		public AspnetRolesBase(System.Guid _applicationId, System.Guid _roleId, System.String _roleName, 
			System.String _loweredRoleName, System.String _description)
		{
			this.entityData = new AspnetRolesEntityData();
			this.backupData = null;

			this.ApplicationId = _applicationId;
			this.RoleId = _roleId;
			this.RoleName = _roleName;
			this.LoweredRoleName = _loweredRoleName;
			this.Description = _description;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="AspnetRoles"/> instance.
		///</summary>
		///<param name="_applicationId"></param>
		///<param name="_roleId"></param>
		///<param name="_roleName"></param>
		///<param name="_loweredRoleName"></param>
		///<param name="_description"></param>
		public static AspnetRoles CreateAspnetRoles(System.Guid _applicationId, System.Guid _roleId, System.String _roleName, 
			System.String _loweredRoleName, System.String _description)
		{
			AspnetRoles newAspnetRoles = new AspnetRoles();
			newAspnetRoles.ApplicationId = _applicationId;
			newAspnetRoles.RoleId = _roleId;
			newAspnetRoles.RoleName = _roleName;
			newAspnetRoles.LoweredRoleName = _loweredRoleName;
			newAspnetRoles.Description = _description;
			return newAspnetRoles;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the ApplicationId property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Guid ApplicationId
		{
			get
			{
				return this.entityData.ApplicationId; 
			}
			
			set
			{
				if (this.entityData.ApplicationId == value)
					return;
					
				OnColumnChanging(AspnetRolesColumn.ApplicationId, this.entityData.ApplicationId);
				this.entityData.ApplicationId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(AspnetRolesColumn.ApplicationId, this.entityData.ApplicationId);
				OnPropertyChanged("ApplicationId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the RoleId property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Guid RoleId
		{
			get
			{
				return this.entityData.RoleId; 
			}
			
			set
			{
				if (this.entityData.RoleId == value)
					return;
					
				OnColumnChanging(AspnetRolesColumn.RoleId, this.entityData.RoleId);
				this.entityData.RoleId = value;
				this.EntityId.RoleId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(AspnetRolesColumn.RoleId, this.entityData.RoleId);
				OnPropertyChanged("RoleId");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the RoleId property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the RoleId property.</remarks>
		/// <value>This type is uniqueidentifier</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Guid OriginalRoleId
		{
			get { return this.entityData.OriginalRoleId; }
			set { this.entityData.OriginalRoleId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the RoleName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[NotNullValidator(MessageTemplate="Property does not allow null values.", Tag="RoleName")]
		[ValidatorComposition(CompositionType.And, Tag="RoleName")]

		[StringLengthValidator(256, MessageTemplate="Maximum length has been exceeded.", Tag="RoleName")]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 256)]
		public virtual System.String RoleName
		{
			get
			{
				return this.entityData.RoleName; 
			}
			
			set
			{
				if (this.entityData.RoleName == value)
					return;
					
				OnColumnChanging(AspnetRolesColumn.RoleName, this.entityData.RoleName);
				this.entityData.RoleName = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(AspnetRolesColumn.RoleName, this.entityData.RoleName);
				OnPropertyChanged("RoleName");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the LoweredRoleName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[NotNullValidator(MessageTemplate="Property does not allow null values.", Tag="LoweredRoleName")]
		[ValidatorComposition(CompositionType.And, Tag="LoweredRoleName")]

		[StringLengthValidator(256, MessageTemplate="Maximum length has been exceeded.", Tag="LoweredRoleName")]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 256)]
		public virtual System.String LoweredRoleName
		{
			get
			{
				return this.entityData.LoweredRoleName; 
			}
			
			set
			{
				if (this.entityData.LoweredRoleName == value)
					return;
					
				OnColumnChanging(AspnetRolesColumn.LoweredRoleName, this.entityData.LoweredRoleName);
				this.entityData.LoweredRoleName = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(AspnetRolesColumn.LoweredRoleName, this.entityData.LoweredRoleName);
				OnPropertyChanged("LoweredRoleName");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Description property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>


		[NotNullValidator(Negated=true, Tag="Description")]
		[ValidatorComposition(CompositionType.Or, Tag="Description")]
		[StringLengthValidator(256, MessageTemplate="Maximum length has been exceeded.", Tag="Description")]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 256)]
		public virtual System.String Description
		{
			get
			{
				return this.entityData.Description; 
			}
			
			set
			{
				if (this.entityData.Description == value)
					return;
					
				OnColumnChanging(AspnetRolesColumn.Description, this.entityData.Description);
				this.entityData.Description = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(AspnetRolesColumn.Description, this.entityData.Description);
				OnPropertyChanged("Description");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="AspnetApplications"/>.
		/// </summary>
		/// <value>The source AspnetApplications for ApplicationId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual AspnetApplications ApplicationIdSource
      	{
            get { return entityData.ApplicationIdSource; }
            set { entityData.ApplicationIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of AspnetUsersInRoles objects
		///	which are related to this object through the relation FK__aspnet_Us__RoleI__37A5467C
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<AspnetUsersInRoles> AspnetUsersInRolesCollection
		{
			get { return entityData.AspnetUsersInRolesCollection; }
			set { entityData.AspnetUsersInRolesCollection = value; }	
		}

		/// <summary>
		///	Holds a collection of AspnetUsersFromAspnetUsersInRoles objects
		///	which are related to this object through the junction table AspnetUsersInRoles
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<AspnetUsers> UserIdAspnetUsersCollection_From_AspnetUsersInRoles
		{
			get { return entityData.UserIdAspnetUsersCollection_From_AspnetUsersInRoles; }
			set { entityData.UserIdAspnetUsersCollection_From_AspnetUsersInRoles = value; }	
		}
		#endregion Children Collections
		
		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "aspnet_Roles"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ApplicationId", "RoleId", "RoleName", "LoweredRoleName", "Description"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as AspnetRolesEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (AspnetRoles) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<AspnetRoles>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as AspnetRoles);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed AspnetRoles Entity 
		///</summary>
		protected virtual AspnetRoles Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			AspnetRoles copy = new AspnetRoles();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.ApplicationId = this.ApplicationId;
				copy.RoleId = this.RoleId;
					copy.OriginalRoleId = this.OriginalRoleId;
				copy.RoleName = this.RoleName;
				copy.LoweredRoleName = this.LoweredRoleName;
				copy.Description = this.Description;
			
			if (this.ApplicationIdSource != null && existingCopies.Contains(this.ApplicationIdSource))
				copy.ApplicationIdSource = existingCopies[this.ApplicationIdSource] as AspnetApplications;
			else
				copy.ApplicationIdSource = MakeCopyOf(this.ApplicationIdSource, existingCopies) as AspnetApplications;
		
			//deep copy nested objects
			copy.AspnetUsersInRolesCollection = (TList<AspnetUsersInRoles>) MakeCopyOf(this.AspnetUsersInRolesCollection, existingCopies); 
			copy.UserIdAspnetUsersCollection_From_AspnetUsersInRoles = (TList<AspnetUsers>) MakeCopyOf(this.UserIdAspnetUsersCollection_From_AspnetUsersInRoles, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed AspnetRoles Entity 
		///</summary>
		public virtual AspnetRoles Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed AspnetRoles Entity which is a deep copy of the current entity.
		///</summary>
		public virtual AspnetRoles DeepCopy()
		{
			return EntityHelper.Clone<AspnetRoles>(this as AspnetRoles);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as AspnetRolesEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new AspnetRolesEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as AspnetRolesEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(AspnetRolesColumn column)
		{
			switch(column)
			{
					case AspnetRolesColumn.ApplicationId:
					return entityData.ApplicationId != _originalData.ApplicationId;
					case AspnetRolesColumn.RoleId:
					return entityData.RoleId != _originalData.RoleId;
					case AspnetRolesColumn.RoleName:
					return entityData.RoleName != _originalData.RoleName;
					case AspnetRolesColumn.LoweredRoleName:
					return entityData.LoweredRoleName != _originalData.LoweredRoleName;
					case AspnetRolesColumn.Description:
					return entityData.Description != _originalData.Description;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< AspnetRolesColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.ApplicationId != _originalData.ApplicationId;
			result = result || entityData.RoleId != _originalData.RoleId;
			result = result || entityData.RoleName != _originalData.RoleName;
			result = result || entityData.LoweredRoleName != _originalData.LoweredRoleName;
			result = result || entityData.Description != _originalData.Description;
			return result;
		}	
		
		///<summary>
		///  Returns a AspnetRoles Entity with the original data.
		///</summary>
		public AspnetRoles GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateAspnetRoles(
				_originalData.ApplicationId,
				_originalData.RoleId,
				_originalData.RoleName,
				_originalData.LoweredRoleName,
				_originalData.Description
				);
				
			return (AspnetRoles)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="AspnetRolesBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is AspnetRolesBase)
				return ValueEquals(this, (AspnetRolesBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="AspnetRolesBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.ApplicationId.GetHashCode() ^ 
					this.RoleId.GetHashCode() ^ 
					this.RoleName.GetHashCode() ^ 
					this.LoweredRoleName.GetHashCode() ^ 
					((this.Description == null) ? string.Empty : this.Description.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="AspnetRolesBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(AspnetRolesBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="AspnetRolesBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="AspnetRolesBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="AspnetRolesBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(AspnetRolesBase Object1, AspnetRolesBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.ApplicationId != Object2.ApplicationId)
				equal = false;
			if (Object1.RoleId != Object2.RoleId)
				equal = false;
			if (Object1.RoleName != Object2.RoleName)
				equal = false;
			if (Object1.LoweredRoleName != Object2.LoweredRoleName)
				equal = false;
			if ( Object1.Description != null && Object2.Description != null )
			{
				if (Object1.Description != Object2.Description)
					equal = false;
			}
			else if (Object1.Description == null ^ Object2.Description == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((AspnetRolesBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static AspnetRolesComparer GetComparer()
        {
            return new AspnetRolesComparer();
        }
        */

        // Comparer delegates back to AspnetRoles
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(AspnetRoles rhs, AspnetRolesColumn which)
        {
            switch (which)
            {
            	
            	
            	case AspnetRolesColumn.ApplicationId:
            		return this.ApplicationId.CompareTo(rhs.ApplicationId);
            		
            		                 
            	
            	
            	case AspnetRolesColumn.RoleId:
            		return this.RoleId.CompareTo(rhs.RoleId);
            		
            		                 
            	
            	
            	case AspnetRolesColumn.RoleName:
            		return this.RoleName.CompareTo(rhs.RoleName);
            		
            		                 
            	
            	
            	case AspnetRolesColumn.LoweredRoleName:
            		return this.LoweredRoleName.CompareTo(rhs.LoweredRoleName);
            		
            		                 
            	
            	
            	case AspnetRolesColumn.Description:
            		return this.Description.CompareTo(rhs.Description);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<AspnetRolesKey> Members
		
		// member variable for the EntityId property
		private AspnetRolesKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual AspnetRolesKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new AspnetRolesKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("AspnetRoles")
					.Append("|").Append( this.RoleId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{6}{5}- ApplicationId: {0}{5}- RoleId: {1}{5}- RoleName: {2}{5}- LoweredRoleName: {3}{5}- Description: {4}{5}{7}", 
				this.ApplicationId,
				this.RoleId,
				this.RoleName,
				this.LoweredRoleName,
				(this.Description == null) ? string.Empty : this.Description.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'aspnet_Roles' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class AspnetRolesEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// RoleId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "aspnet_Roles"</remarks>
		public System.Guid RoleId;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.Guid OriginalRoleId;
		
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// ApplicationId : 
		/// </summary>
		public System.Guid		  ApplicationId = Guid.Empty;
		
		/// <summary>
		/// RoleName : 
		/// </summary>
		public System.String		  RoleName = string.Empty;
		
		/// <summary>
		/// LoweredRoleName : 
		/// </summary>
		public System.String		  LoweredRoleName = string.Empty;
		
		/// <summary>
		/// Description : 
		/// </summary>
		public System.String		  Description = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private AspnetApplications _applicationIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="AspnetApplications"/>.
		/// </summary>
		/// <value>The source AspnetApplications for ApplicationId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual AspnetApplications ApplicationIdSource
      	{
            get { return this._applicationIdSource; }
            set { this._applicationIdSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#region AspnetUsersInRolesCollection
		
		private TList<AspnetUsersInRoles> _aspnetUsersInRolesRoleId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _aspnetUsersInRolesRoleId
		/// </summary>
		
		public TList<AspnetUsersInRoles> AspnetUsersInRolesCollection
		{
			get
			{
				if (_aspnetUsersInRolesRoleId == null)
				{
				_aspnetUsersInRolesRoleId = new TList<AspnetUsersInRoles>();
				}
	
				return _aspnetUsersInRolesRoleId;
			}
			set { _aspnetUsersInRolesRoleId = value; }
		}
		
		#endregion

		#region UserIdAspnetUsersCollection_From_AspnetUsersInRoles
		
		private TList<AspnetUsers> userIdAspnetUsersCollectionFromAspnetUsersInRoles;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the junction table userIdAspnetUsersCollectionFromAspnetUsersInRoles
		/// </summary>
		
		public TList<AspnetUsers> UserIdAspnetUsersCollection_From_AspnetUsersInRoles
		{
			get
			{
				if (userIdAspnetUsersCollectionFromAspnetUsersInRoles == null)
				{
				userIdAspnetUsersCollectionFromAspnetUsersInRoles = new TList<AspnetUsers>();
				}
	
				return userIdAspnetUsersCollectionFromAspnetUsersInRoles;
			}
			set { userIdAspnetUsersCollectionFromAspnetUsersInRoles = value; }
		}
		
		#endregion 

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			AspnetRolesEntityData _tmp = new AspnetRolesEntityData();
						
			_tmp.RoleId = this.RoleId;
			_tmp.OriginalRoleId = this.OriginalRoleId;
			
			_tmp.ApplicationId = this.ApplicationId;
			_tmp.RoleName = this.RoleName;
			_tmp.LoweredRoleName = this.LoweredRoleName;
			_tmp.Description = this.Description;
			
			#region Source Parent Composite Entities
			if (this.ApplicationIdSource != null)
				_tmp.ApplicationIdSource = MakeCopyOf(this.ApplicationIdSource) as AspnetApplications;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._aspnetUsersInRolesRoleId != null)
				_tmp.AspnetUsersInRolesCollection = (TList<AspnetUsersInRoles>) MakeCopyOf(this.AspnetUsersInRolesCollection); 
			if (this.userIdAspnetUsersCollectionFromAspnetUsersInRoles != null)
				_tmp.UserIdAspnetUsersCollection_From_AspnetUsersInRoles = (TList<AspnetUsers>) MakeCopyOf(this.UserIdAspnetUsersCollection_From_AspnetUsersInRoles); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			AspnetRolesEntityData _tmp = new AspnetRolesEntityData();
						
			_tmp.RoleId = this.RoleId;
			_tmp.OriginalRoleId = this.OriginalRoleId;
			
			_tmp.ApplicationId = this.ApplicationId;
			_tmp.RoleName = this.RoleName;
			_tmp.LoweredRoleName = this.LoweredRoleName;
			_tmp.Description = this.Description;
			
			#region Source Parent Composite Entities
			if (this.ApplicationIdSource != null && existingCopies.Contains(this.ApplicationIdSource))
				_tmp.ApplicationIdSource = existingCopies[this.ApplicationIdSource] as AspnetApplications;
			else
				_tmp.ApplicationIdSource = MakeCopyOf(this.ApplicationIdSource, existingCopies) as AspnetApplications;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.AspnetUsersInRolesCollection = (TList<AspnetUsersInRoles>) MakeCopyOf(this.AspnetUsersInRolesCollection, existingCopies); 
			_tmp.UserIdAspnetUsersCollection_From_AspnetUsersInRoles = (TList<AspnetUsers>) MakeCopyOf(this.UserIdAspnetUsersCollection_From_AspnetUsersInRoles, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="AspnetRolesColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(AspnetRolesColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="AspnetRolesColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(AspnetRolesColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="AspnetRolesColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(AspnetRolesColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				AspnetRolesEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new AspnetRolesEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="AspnetRolesColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(AspnetRolesColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				AspnetRolesEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new AspnetRolesEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region AspnetRolesEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="AspnetRoles"/> object.
	/// </remarks>
	public class AspnetRolesEventArgs : System.EventArgs
	{
		private AspnetRolesColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the AspnetRolesEventArgs class.
		///</summary>
		public AspnetRolesEventArgs(AspnetRolesColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the AspnetRolesEventArgs class.
		///</summary>
		public AspnetRolesEventArgs(AspnetRolesColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The AspnetRolesColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="AspnetRolesColumn" />
		public AspnetRolesColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all AspnetRoles related events.
	///</summary>
	public delegate void AspnetRolesEventHandler(object sender, AspnetRolesEventArgs e);
	
	#region AspnetRolesComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class AspnetRolesComparer : System.Collections.Generic.IComparer<AspnetRoles>
	{
		AspnetRolesColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:AspnetRolesComparer"/> class.
        /// </summary>
		public AspnetRolesComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:AspnetRolesComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public AspnetRolesComparer(AspnetRolesColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="AspnetRoles"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="AspnetRoles"/> to compare.</param>
        /// <param name="b">The second <c>AspnetRoles</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(AspnetRoles a, AspnetRoles b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(AspnetRoles entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(AspnetRoles a, AspnetRoles b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public AspnetRolesColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region AspnetRolesKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="AspnetRoles"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class AspnetRolesKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the AspnetRolesKey class.
		/// </summary>
		public AspnetRolesKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the AspnetRolesKey class.
		/// </summary>
		public AspnetRolesKey(AspnetRolesBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.RoleId = entity.RoleId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the AspnetRolesKey class.
		/// </summary>
		public AspnetRolesKey(System.Guid _roleId)
		{
			#region Init Properties

			this.RoleId = _roleId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private AspnetRolesBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public AspnetRolesBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the RoleId property
		private System.Guid _roleId;
		
		/// <summary>
		/// Gets or sets the RoleId property.
		/// </summary>
		public System.Guid RoleId
		{
			get { return _roleId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.RoleId = value;
				
				_roleId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				RoleId = ( values["RoleId"] != null ) ? (System.Guid) EntityUtil.ChangeType(values["RoleId"], typeof(System.Guid)) : Guid.Empty;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("RoleId", RoleId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("RoleId: {0}{1}",
								RoleId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region AspnetRolesColumn Enum
	
	/// <summary>
	/// Enumerate the AspnetRoles columns.
	/// </summary>
	[Serializable]
	public enum AspnetRolesColumn : int
	{
		/// <summary>
		/// ApplicationId : 
		/// </summary>
		[EnumTextValue("ApplicationId")]
		[ColumnEnum("ApplicationId", typeof(System.Guid), System.Data.DbType.Guid, false, false, false)]
		ApplicationId = 1,
		/// <summary>
		/// RoleId : 
		/// </summary>
		[EnumTextValue("RoleId")]
		[ColumnEnum("RoleId", typeof(System.Guid), System.Data.DbType.Guid, true, false, false)]
		RoleId = 2,
		/// <summary>
		/// RoleName : 
		/// </summary>
		[EnumTextValue("RoleName")]
		[ColumnEnum("RoleName", typeof(System.String), System.Data.DbType.String, false, false, false, 256)]
		RoleName = 3,
		/// <summary>
		/// LoweredRoleName : 
		/// </summary>
		[EnumTextValue("LoweredRoleName")]
		[ColumnEnum("LoweredRoleName", typeof(System.String), System.Data.DbType.String, false, false, false, 256)]
		LoweredRoleName = 4,
		/// <summary>
		/// Description : 
		/// </summary>
		[EnumTextValue("Description")]
		[ColumnEnum("Description", typeof(System.String), System.Data.DbType.String, false, false, true, 256)]
		Description = 5
	}//End enum

	#endregion AspnetRolesColumn Enum

} // end namespace
