using System;
using System.ComponentModel;

namespace NDMSInvestigation.Entities
{
	/// <summary>
	///		The data structure representation of the 'aspnet_WebEvent_Events' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IAspnetWebEventEvents 
	{
		/// <summary>			
		/// EventId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "aspnet_WebEvent_Events"</remarks>
		System.String EventId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.String OriginalEventId { get; set; }
			
		
		
		/// <summary>
		/// EventTimeUtc : 
		/// </summary>
		System.DateTime  EventTimeUtc  { get; set; }
		
		/// <summary>
		/// EventTime : 
		/// </summary>
		System.DateTime  EventTime  { get; set; }
		
		/// <summary>
		/// EventType : 
		/// </summary>
		System.String  EventType  { get; set; }
		
		/// <summary>
		/// EventSequence : 
		/// </summary>
		System.Decimal  EventSequence  { get; set; }
		
		/// <summary>
		/// EventOccurrence : 
		/// </summary>
		System.Decimal  EventOccurrence  { get; set; }
		
		/// <summary>
		/// EventCode : 
		/// </summary>
		System.Int32  EventCode  { get; set; }
		
		/// <summary>
		/// EventDetailCode : 
		/// </summary>
		System.Int32  EventDetailCode  { get; set; }
		
		/// <summary>
		/// Message : 
		/// </summary>
		System.String  Message  { get; set; }
		
		/// <summary>
		/// ApplicationPath : 
		/// </summary>
		System.String  ApplicationPath  { get; set; }
		
		/// <summary>
		/// ApplicationVirtualPath : 
		/// </summary>
		System.String  ApplicationVirtualPath  { get; set; }
		
		/// <summary>
		/// MachineName : 
		/// </summary>
		System.String  MachineName  { get; set; }
		
		/// <summary>
		/// RequestUrl : 
		/// </summary>
		System.String  RequestUrl  { get; set; }
		
		/// <summary>
		/// ExceptionType : 
		/// </summary>
		System.String  ExceptionType  { get; set; }
		
		/// <summary>
		/// Details : 
		/// </summary>
		System.String  Details  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


