using System;
using System.ComponentModel;

namespace NDMSInvestigation.Entities
{
	/// <summary>
	///		The data structure representation of the 'QuestionDetails' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IQuestionDetails 
	{
		/// <summary>			
		/// QuestionId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "QuestionDetails"</remarks>
		System.Int32 QuestionId { get; set; }
				
		
		
		/// <summary>
		/// QuestionContent : 
		/// </summary>
		System.String  QuestionContent  { get; set; }
		
		/// <summary>
		/// QuestionSuggest : 
		/// </summary>
		System.String  QuestionSuggest  { get; set; }
		
		/// <summary>
		/// QuestionDescription : 
		/// </summary>
		System.String  QuestionDescription  { get; set; }
		
		/// <summary>
		/// OrderNumber : 
		/// </summary>
		System.Int32?  OrderNumber  { get; set; }
		
		/// <summary>
		/// GroupId : 
		/// </summary>
		System.Int32?  GroupId  { get; set; }
		
		/// <summary>
		/// CreatedDate : 
		/// </summary>
		System.DateTime?  CreatedDate  { get; set; }
		
		/// <summary>
		/// CreatedBy : 
		/// </summary>
		System.String  CreatedBy  { get; set; }
		
		/// <summary>
		/// UpdatedDate : 
		/// </summary>
		System.DateTime?  UpdatedDate  { get; set; }
		
		/// <summary>
		/// UpdatedBy : 
		/// </summary>
		System.String  UpdatedBy  { get; set; }
		
		/// <summary>
		/// QuestionTitle : 
		/// </summary>
		System.String  QuestionTitle  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _questionAnswerQuestionId
		/// </summary>	
		TList<QuestionAnswer> QuestionAnswerCollection {  get;  set;}	

		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the junction table answerIdAnswerDetailsCollectionFromQuestionAnswer
		/// </summary>	
		TList<AnswerDetails> AnswerIdAnswerDetailsCollection_From_QuestionAnswer { get; set; }	

		#endregion Data Properties

	}
}


